{{- if or (eq .Values.global.scheduler.enabled true) (eq .Values.global.reminders.serviceName "scheduler") }}
kind: Service
apiVersion: v1
metadata:
  name: dapr-scheduler-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: dapr-scheduler-server
    {{- range $key, $value := .Values.global.k8sLabels }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4}}
{{- end }}
spec:
  selector:
    app: dapr-scheduler-server
  # scheduler must be able to resolve pod address to join initial cluster peers
  # before POD is ready
  publishNotReadyAddresses: true
  ports:
  - name: api
    port: {{ .Values.ports.apiPort }}
  - name: raft-node
    port: {{ .Values.ports.etcdRPCPort }}
  clusterIP: None
{{- end }}